### ISSUE TITLE
Add `custom.scss` to theme so we can fix color-contrast issues present in Sandstone

### ISSUE THREAD

**Issue by batpigandme** [juliasilge/vetiver.dev#10]
To be discussed, and, again, I'm happy to do a PR for this once we've decided what changes we want to make.

Can also be called `theme.scss` or whatever (I just call it `custom.scss` for my stuff).

Here's how they do this [for the Quarto website](https://github.com/batpigandme/quarto-web/blob/8b104b1adba2cd59e9927373a730a88c0b945a3d/_quarto.yml#L379-L383):

```yaml
format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
```
