### ISSUE TITLE
Use `aria-label` YAML when using icon links

### ISSUE THREAD

**Issue by batpigandme** [juliasilge/vetiver.dev#9]
Undersung hero (parameter/option) is that you can actually add an `aria-label` to the icon links:
https://github.com/juliasilge/vetiver.dev/blob/4424dadcf46e5a1cf9bf40784ebe4dc6b31c3381/_quarto.yml#L23-L24

So, for example, in the Quarto website `_quarto.yml` I added:
```
    right:
      - icon: twitter
        href: https://twitter.com/quarto_pub
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        aria-label: Quarto GitHub
```

For when those two are used in the navbar and footer. (Again, I can put in a PR for this)
